spring:
  application:
    name: demo2
  datasource:
    url: jdbc:postgresql://localhost:5432/demo1
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    datasource:
      initialization-mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password